import React, { useState } from 'react';
import { useAuth } from '../../contexts/AuthContext';
import { generateReport } from '../../services/api';
import { 
  Line, 
  Bar, 
  Pie 
} from 'react-chartjs-2';
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  BarElement,
  ArcElement,
  Title,
  Tooltip,
  Legend,
  Filler
} from 'chart.js';
import toast from 'react-hot-toast';

ChartJS.register(
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  BarElement,
  ArcElement,
  Title,
  Tooltip,
  Legend,
  Filler
);

const AdminReports = () => {
  const { user } = useAuth();
  const [generating, setGenerating] = useState(false);
  const [reportData, setReportData] = useState(null);
  const [reportType, setReportType] = useState('users');
  const [format, setFormat] = useState('json');
  const [filters, setFilters] = useState({
    role: 'all',
    status: 'all'
  });

  const handleGenerate = async () => {
    setGenerating(true);
    try {
      const response = await generateReport({
        type: reportType,
        format: format,
        filters: filters
      });
      setReportData(response.data.data);
      toast.success('Report generated successfully');
    } catch (error) {
      console.error('Error generating report:', error);
      toast.error(error.response?.data?.message || 'Failed to generate report');
    } finally {
      setGenerating(false);
    }
  };

  const downloadCSV = () => {
    if (!reportData?.data || reportData.data.length === 0) {
      toast.error('No data to download');
      return;
    }
    
    // Add watermark header
    const watermark = `# TEYZIX Report\n# Generated by: ${user?.name}\n# Generated on: ${new Date().toLocaleString()}\n# Report Type: ${reportType.toUpperCase()}\n# Total Records: ${reportData.data.length}\n${'='.repeat(60)}\n\n`;
    
    const headers = Object.keys(reportData.data[0]);
    const csvRows = [];
    csvRows.push(headers.join(','));
    
    for (const row of reportData.data) {
      const values = headers.map(header => {
        const value = row[header] || '';
        return `"${String(value).replace(/"/g, '""')}"`;
      });
      csvRows.push(values.join(','));
    }
    
    // Add footer watermark
    const footer = `\n\n${'='.repeat(60)}\n# End of Report\n# © TEYZIX Marketplace - All Rights Reserved\n# Generated on: ${new Date().toLocaleString()}`;
    
    const csvContent = watermark + csvRows.join('\n') + footer;
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `TEYZIX_${reportType}_report_${new Date().toISOString().split('T')[0]}.csv`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success('Report downloaded as CSV with watermark');
  };

  const downloadJSON = () => {
    if (!reportData) {
      toast.error('No data to download');
      return;
    }
    
    const jsonWithWatermark = {
      watermark: {
        platform: 'TEYZIX Marketplace',
        generatedBy: user?.name,
        generatedByEmail: user?.email,
        generatedAt: new Date().toISOString(),
        reportType: reportType,
        reportFormat: 'JSON',
        totalRecords: reportData.data?.length || 0,
        copyright: '© TEYZIX - All Rights Reserved'
      },
      logo: {
        name: 'TEYZIX',
        url: 'https://teyzix.com/logo.png',
        tagline: "Nepal's #1 Service Marketplace"
      },
      reportData: reportData,
      footer: {
        message: 'This report is confidential and generated by TEYZIX platform',
        support: 'For questions, contact support@teyzix.com',
        generatedOn: new Date().toLocaleString()
      }
    };
    
    const dataStr = JSON.stringify(jsonWithWatermark, null, 2);
    const blob = new Blob([dataStr], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `TEYZIX_${reportType}_report_${new Date().toISOString().split('T')[0]}.json`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success('Report downloaded as JSON with watermark');
  };

  // Chart data for revenue report
  const getLineChartData = () => {
    if (reportType !== 'revenue' || !reportData?.monthlyRevenue) return null;
    
    return {
      labels: reportData.monthlyRevenue.map(m => {
        const [year, month] = m.month.split('-');
        const date = new Date(year, parseInt(month) - 1);
        return date.toLocaleString('default', { month: 'short', year: 'numeric' });
      }),
      datasets: [
        {
          label: 'Monthly Revenue (NPR)',
          data: reportData.monthlyRevenue.map(m => m.revenue),
          fill: true,
          backgroundColor: 'rgba(99, 102, 241, 0.1)',
          borderColor: 'rgb(99, 102, 241)',
          tension: 0.4,
          pointBackgroundColor: 'rgb(99, 102, 241)',
          pointBorderColor: '#fff',
          pointHoverRadius: 8,
          pointRadius: 4,
        }
      ]
    };
  };

  // Bar chart data for revenue by project
  const getBarChartData = () => {
    if (reportType !== 'revenue') return null;
    
    return {
      labels: ['Total Revenue', 'Platform Commission', 'Provider Earnings'],
      datasets: [
        {
          label: 'Amount (NPR)',
          data: [
            reportData?.totalRevenue || 0,
            reportData?.platformCommission || 0,
            (reportData?.totalRevenue || 0) - (reportData?.platformCommission || 0)
          ],
          backgroundColor: [
            'rgba(16, 185, 129, 0.8)',
            'rgba(99, 102, 241, 0.8)',
            'rgba(245, 158, 11, 0.8)'
          ],
          borderColor: [
            'rgb(16, 185, 129)',
            'rgb(99, 102, 241)',
            'rgb(245, 158, 11)'
          ],
          borderWidth: 1,
        }
      ]
    };
  };

  // Pie chart data for status distribution
  const getPieChartData = () => {
    if (reportType !== 'requests' && reportType !== 'services') return null;
    
    let labels = [];
    let data = [];
    let backgroundColors = [];
    
    if (reportType === 'requests') {
      const statusCounts = {};
      reportData?.data?.forEach(r => {
        statusCounts[r.Status] = (statusCounts[r.Status] || 0) + 1;
      });
      labels = Object.keys(statusCounts);
      data = Object.values(statusCounts);
      backgroundColors = ['#f59e0b', '#3b82f6', '#8b5cf6', '#10b981', '#06b6d4', '#ef4444'];
    } else if (reportType === 'services') {
      const categoryCounts = {};
      reportData?.data?.forEach(s => {
        categoryCounts[s.Category] = (categoryCounts[s.Category] || 0) + 1;
      });
      labels = Object.keys(categoryCounts);
      data = Object.values(categoryCounts);
      backgroundColors = ['#6366f1', '#8b5cf6', '#ec4899', '#f43f5e', '#f97316', '#10b981'];
    }
    
    return {
      labels,
      datasets: [
        {
          data,
          backgroundColor: backgroundColors.slice(0, labels.length),
          borderColor: '#fff',
          borderWidth: 2,
        }
      ]
    };
  };

  const chartOptions = {
    responsive: true,
    maintainAspectRatio: false,
    plugins: {
      legend: {
        position: 'top',
        labels: {
          color: '#6b7280',
          font: { size: 12 }
        }
      },
      tooltip: {
        callbacks: {
          label: (context) => {
            let label = context.dataset.label || '';
            let value = context.raw;
            if (reportType === 'revenue') {
              return `${label}: रू ${value.toLocaleString('ne-NP')}`;
            }
            return `${label}: ${value}`;
          }
        }
      }
    },
    scales: reportType === 'revenue' ? {
      y: {
        ticks: {
          callback: (value) => `रू ${value.toLocaleString('ne-NP')}`
        }
      }
    } : {}
  };

  const reportTypes = [
    { value: 'users', label: 'Users Report', icon: '👥', description: 'All registered users with details' },
    { value: 'services', label: 'Services Report', icon: '🛍️', description: 'All services with status and provider info' },
    { value: 'requests', label: 'Projects Report', icon: '📋', description: 'All projects with customer and provider details' },
    { value: 'reviews', label: 'Reviews Report', icon: '⭐', description: 'All reviews with ratings and comments' },
    { value: 'revenue', label: 'Revenue Report', icon: '💰', description: 'Platform revenue and earnings summary' },
    { value: 'disputes', label: 'Disputes Report', icon: '⚖️', description: 'All disputes with resolution status' }
  ];

  return (
    <div>
      <h1 className="text-2xl font-bold text-gray-900 dark:text-white mb-2">Report Generator</h1>
      <p className="text-gray-500 dark:text-gray-400 mb-6">Generate and export platform reports with charts</p>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Report Type Selection */}
        <div className="lg:col-span-2 bg-white dark:bg-gray-800 rounded-xl p-6 shadow-sm">
          <h2 className="text-lg font-semibold text-gray-900 dark:text-white mb-4">Select Report Type</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
            {reportTypes.map(type => (
              <button
                key={type.value}
                onClick={() => {
                  setReportType(type.value);
                  setReportData(null);
                }}
                className={`p-4 rounded-xl border-2 text-left transition-all ${
                  reportType === type.value
                    ? 'border-indigo-600 bg-indigo-50 dark:bg-indigo-900/20'
                    : 'border-gray-200 dark:border-gray-700 hover:border-indigo-300'
                }`}
              >
                <div className="text-3xl mb-2">{type.icon}</div>
                <div className="font-semibold text-gray-900 dark:text-white">{type.label}</div>
                <div className="text-xs text-gray-500 mt-1">{type.description}</div>
              </button>
            ))}
          </div>
        </div>

        {/* Report Settings */}
        <div className="bg-white dark:bg-gray-800 rounded-xl p-6 shadow-sm">
          <h2 className="text-lg font-semibold text-gray-900 dark:text-white mb-4">Report Settings</h2>
          
          <div className="mb-4">
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">Download Format</label>
            <div className="flex gap-3">
              {['json', 'csv'].map(f => (
                <label key={f} className="flex items-center gap-2 cursor-pointer">
                  <input
                    type="radio"
                    value={f}
                    checked={format === f}
                    onChange={(e) => setFormat(e.target.value)}
                    className="text-indigo-600"
                  />
                  <span className="text-sm capitalize">{f.toUpperCase()}</span>
                </label>
              ))}
            </div>
          </div>

          {(reportType === 'users' || reportType === 'services' || reportType === 'requests') && (
            <div className="mb-4">
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                {reportType === 'users' ? 'Filter by Role' : reportType === 'services' ? 'Filter by Status' : 'Filter by Status'}
              </label>
              <select
                value={filters.role}
                onChange={(e) => setFilters({ ...filters, role: e.target.value })}
                className="w-full px-3 py-2 rounded-lg border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-700 text-sm"
              >
                <option value="all">All</option>
                {reportType === 'users' ? (
                  <>
                    <option value="customer">Customer</option>
                    <option value="provider">Provider</option>
                    <option value="admin">Admin</option>
                  </>
                ) : (
                  <>
                    <option value="approved">Approved</option>
                    <option value="pending">Pending</option>
                    <option value="rejected">Rejected</option>
                  </>
                )}
              </select>
            </div>
          )}

          <button
            onClick={handleGenerate}
            disabled={generating}
            className="w-full py-3 bg-gradient-to-r from-indigo-600 to-purple-600 text-white font-semibold rounded-xl hover:from-indigo-700 hover:to-purple-700 transition-colors disabled:opacity-50"
          >
            {generating ? (
              <span className="flex items-center justify-center gap-2">
                <div className="animate-spin h-4 w-4 border-2 border-white rounded-full border-t-transparent"></div>
                Generating...
              </span>
            ) : (
              'Generate Report →'
            )}
          </button>
        </div>
      </div>

      {/* Report Results with Charts */}
      {reportData && (
        <div className="mt-8 space-y-6">
          {/* Summary Cards */}
          <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
            {reportType === 'revenue' && (
              <>
                <div className="bg-white dark:bg-gray-800 rounded-xl p-4 text-center shadow-sm border border-gray-200 dark:border-gray-700">
                  <div className="text-2xl font-bold text-indigo-600">
                    रू {reportData.totalRevenue?.toLocaleString()}
                  </div>
                  <div className="text-xs text-gray-500">Total Revenue</div>
                </div>
                <div className="bg-white dark:bg-gray-800 rounded-xl p-4 text-center shadow-sm border border-gray-200 dark:border-gray-700">
                  <div className="text-2xl font-bold text-purple-600">
                    रू {reportData.platformCommission?.toLocaleString()}
                  </div>
                  <div className="text-xs text-gray-500">Platform Commission (10%)</div>
                </div>
                <div className="bg-white dark:bg-gray-800 rounded-xl p-4 text-center shadow-sm border border-gray-200 dark:border-gray-700">
                  <div className="text-2xl font-bold text-green-600">
                    {reportData.projectCount}
                  </div>
                  <div className="text-xs text-gray-500">Completed Projects</div>
                </div>
                <div className="bg-white dark:bg-gray-800 rounded-xl p-4 text-center shadow-sm border border-gray-200 dark:border-gray-700">
                  <div className="text-2xl font-bold text-yellow-600">
                    रू {reportData.averageProjectValue?.toLocaleString()}
                  </div>
                  <div className="text-xs text-gray-500">Average Project Value</div>
                </div>
              </>
            )}
            
            {reportType !== 'revenue' && reportData.data && (
              <div className="bg-white dark:bg-gray-800 rounded-xl p-4 text-center shadow-sm border border-gray-200 dark:border-gray-700 col-span-4">
                <div className="text-3xl font-bold text-indigo-600">{reportData.count}</div>
                <div className="text-sm text-gray-500">Total {reportType.charAt(0).toUpperCase() + reportType.slice(1)} Records</div>
              </div>
            )}
          </div>

          {/* Charts Section */}
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            {/* Line Chart - Monthly Revenue Trend */}
            {reportType === 'revenue' && getLineChartData() && (
              <div className="bg-white dark:bg-gray-800 rounded-xl p-4 shadow-sm border border-gray-200 dark:border-gray-700">
                <h3 className="font-semibold text-gray-900 dark:text-white mb-4">📈 Monthly Revenue Trend</h3>
                <div className="h-80">
                  <Line data={getLineChartData()} options={chartOptions} />
                </div>
              </div>
            )}

            {/* Bar Chart - Revenue Breakdown */}
            {reportType === 'revenue' && getBarChartData() && (
              <div className="bg-white dark:bg-gray-800 rounded-xl p-4 shadow-sm border border-gray-200 dark:border-gray-700">
                <h3 className="font-semibold text-gray-900 dark:text-white mb-4">📊 Revenue Breakdown</h3>
                <div className="h-80">
                  <Bar data={getBarChartData()} options={chartOptions} />
                </div>
              </div>
            )}

            {/* Pie Chart - Status/Category Distribution */}
            {getPieChartData() && (
              <div className="bg-white dark:bg-gray-800 rounded-xl p-4 shadow-sm border border-gray-200 dark:border-gray-700">
                <h3 className="font-semibold text-gray-900 dark:text-white mb-4">
                  🥧 {reportType === 'requests' ? 'Project Status Distribution' : 'Service Category Distribution'}
                </h3>
                <div className="h-80">
                  <Pie data={getPieChartData()} options={chartOptions} />
                </div>
              </div>
            )}

            {/* Data Table */}
            <div className={`bg-white dark:bg-gray-800 rounded-xl p-4 shadow-sm border border-gray-200 dark:border-gray-700 ${reportType === 'revenue' ? 'lg:col-span-2' : ''}`}>
              <h3 className="font-semibold text-gray-900 dark:text-white mb-4">📋 Report Data</h3>
              <div className="overflow-x-auto max-h-96">
                <table className="w-full text-sm">
                  <thead className="bg-gray-50 dark:bg-gray-700 sticky top-0">
                    <tr>
                      {reportData.data && reportData.data.length > 0 && Object.keys(reportData.data[0]).map(key => (
                        <th key={key} className="px-3 py-2 text-left text-xs font-medium text-gray-500 uppercase">{key}</th>
                      ))}
                      {reportType === 'revenue' && (
                        <>
                          <th className="px-3 py-2 text-left text-xs font-medium text-gray-500 uppercase">Metric</th>
                          <th className="px-3 py-2 text-left text-xs font-medium text-gray-500 uppercase">Value (NPR)</th>
                        </>
                      )}
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-gray-200 dark:divide-gray-700">
                    {reportData.data && reportData.data.slice(0, 10).map((row, idx) => (
                      <tr key={idx} className="hover:bg-gray-50 dark:hover:bg-gray-700/50">
                        {Object.values(row).map((val, i) => (
                          <td key={i} className="px-3 py-2 text-gray-600 dark:text-gray-400">{val}</td>
                        ))}
                      </tr>
                    ))}
                    {reportType === 'revenue' && (
                      <>
                        <tr className="bg-indigo-50 dark:bg-indigo-900/20">
                          <td className="px-3 py-2 font-medium">Total Revenue</td>
                          <td className="px-3 py-2 text-indigo-600 font-semibold">रू {reportData.totalRevenue?.toLocaleString()}</td>
                        </tr>
                        <tr className="bg-purple-50 dark:bg-purple-900/20">
                          <td className="px-3 py-2 font-medium">Platform Commission (10%)</td>
                          <td className="px-3 py-2 text-purple-600 font-semibold">रू {reportData.platformCommission?.toLocaleString()}</td>
                        </tr>
                        <tr className="bg-green-50 dark:bg-green-900/20">
                          <td className="px-3 py-2 font-medium">Provider Earnings</td>
                          <td className="px-3 py-2 text-green-600 font-semibold">रू {(reportData.totalRevenue - reportData.platformCommission)?.toLocaleString()}</td>
                        </tr>
                      </>
                    )}
                  </tbody>
                </table>
                {reportData.data && reportData.data.length > 10 && (
                  <p className="text-xs text-gray-500 text-center py-2">Showing 10 of {reportData.data.length} records</p>
                )}
              </div>
            </div>
          </div>

          {/* Download Buttons with Watermark Info */}
          <div className="bg-gradient-to-r from-indigo-50 to-purple-50 dark:from-gray-800 dark:to-gray-800 rounded-xl p-4">
            <div className="flex justify-between items-center flex-wrap gap-4">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 bg-gradient-to-r from-indigo-600 to-purple-600 rounded-lg flex items-center justify-center">
                  <span className="text-white text-lg">⚡</span>
                </div>
                <div>
                  <p className="font-semibold text-gray-900 dark:text-white">TEYZIX Report</p>
                  <p className="text-xs text-gray-500">Watermarked with platform credentials</p>
                </div>
              </div>
              <div className="flex gap-3">
                {format === 'csv' && (
                  <button
                    onClick={downloadCSV}
                    className="px-5 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 transition-colors flex items-center gap-2"
                  >
                    <span>📥</span> Download CSV
                  </button>
                )}
                {format === 'json' && (
                  <button
                    onClick={downloadJSON}
                    className="px-5 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors flex items-center gap-2"
                  >
                    <span>📥</span> Download JSON
                  </button>
                )}
              </div>
            </div>
            <div className="mt-3 pt-3 border-t border-gray-200 dark:border-gray-700">
              <p className="text-xs text-gray-500 text-center">
                © {new Date().getFullYear()} TEYZIX Marketplace - All downloaded reports include watermark with your credentials
              </p>
            </div>
          </div>
        </div>
      )}

      {/* Tips Section */}
      <div className="mt-6 p-4 bg-indigo-50 dark:bg-indigo-900/20 rounded-xl">
        <div className="flex items-start gap-3">
          <div className="text-2xl">💡</div>
          <div>
            <h3 className="font-semibold text-indigo-800 dark:text-indigo-300">Report Tips</h3>
            <ul className="text-sm text-indigo-700 dark:text-indigo-400 mt-1 space-y-1">
              <li>• Select report type to generate data instantly</li>
              <li>• View interactive charts for visual data representation</li>
              <li>• Download as CSV for Excel or JSON for API integration</li>
              <li>• All downloads include TEYZIX watermark and timestamp</li>
              <li>• Revenue report includes monthly trends and breakdown charts</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
};

export default AdminReports;